version: "3.7"

# Common context for all services
x-common-dev: &common-JumiaABmicroservices
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - ./:/JumiaABmicroservices

services:
  arangodb:
    image: arangodb:3.7
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8530:8529
    volumes:
      - db_container:/var/lib/arangodb3


  servicea:
    <<: *common-JumiaABmicroservices
    command: go run ./service_A
    environment:
      APP_PORT: 60001
    ports:
      - 60005:60001
    links:
      - arangodb
      
  serviceb:
    <<: *common-JumiaABmicrosevices
    command: go run ./service_B
    environment:
      ARANGODB_DB: jumiaabmicroservice_orders
      APP_PORT: 60001
    ports:
      - 60001:60001
    links:
      - arangodb
      - servicea

  
  graphql:
    <<: *common-JumiaABmicroservices
    command: go run ./graph_api
    environment:
      SERVICEB_SERVICE: serviceb:60001
      GRAPH_API_PORT: 80
    ports:
      - 80:80
    links:
      - serviceb
      

volumes:
  db_container:
