version: "3.7"

#creating a common contexxt for all our services
x-common-dev: &common-JumiaABmicroservices      // Go codebase
  build:
    context: .
    dockerfile: Dockerfile.dev           // Our containers decsription and a set of operations that will be executes once compposition is complete
  volumes:
    - ./:/JumiaABmicroservices

services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8530:8529
    volumes:
      - db_container:/var/lib/arangodb3
    

  service_A:
    <<: *common-JumiaABmicroservices
    command: go run ./service_A
    environment:
      ARANGODB_DB: jumia_ab_microservices
      APP_PORT: 60001
    ports:
      - 60001:60001
      
  service_B:
    <<: *common-JumiaABmicroservices
    command: go run ./service_B
    environment:
      ARANGODB_DB: jumia_ab_microservice
      APP_PORT: 60001
    ports:
      - 60005:60001
    links:
      - arangodb

  graphql:
    <<: *common-JumiaABmicroservices
    command: go run ./graph_api
    environment:
      SERVICEB_SERVICE: service_B:60001
      GRAPH_API_PORT: 80
    ports:
      - 80:80
    links:
      - service_B

volumes:
  db_container:

   
