From golang:1.18-stretch   

WORKDIR /microservices4jumia

#copying all dependencies to the container
COPY   go.* .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
#Exposing ports that will be available from the container
EXPOSE 8080
EXPOSE 60001
EXPOSE 60002

#Installing a work directory inside the container
WORKDIR /microservices4jumia
