From golang:1.18-stretch   

WORKDIR /JumiaABmicroservices

#copying all dependencies to the container
COPY   ./go.mod  .
COPY   ./go.sum  .

RUN go mod download

#Exposing ports that will be available from the container
EXPOSE 8080
EXPOSE 60001
EXPOSE 60002

#Installing a work directory inside the container
WORKDIR /JumiaABmicroservices
